# Generated by Django 5.0.6 on 2026-09-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_tip_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
