# Generated by Django 5.0.6 on 2026-09-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herocarousel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_type', models.CharField(choices=[('top_pick', 'Top Pick - Mechi ya Leo'), ('derby', 'Derby - Mechi Kubwa'), ('track_record', 'Track Record - Takwimu ya AI'), ('pro', 'PRO - Subscription Promotion'), ('mic', 'Fan of Match - MIC'), ('did_you_know', 'Did You Know - Facts')], help_text='Aina ya slide ambayo picha hii inatumika', max_length=20, unique=True)),
                ('image_url', models.URLField(help_text='URL ya picha kutoka Cloudinary', max_length=500)),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='Cloudinary public ID kwa ajili ya kubadilisha picha', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'herocarousel_heroimageconfig',
                'ordering': ['slide_type'],
            },
        ),
    ]
