# Generated by Django 5.0.6 on 2026-09-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_adminactionlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('BAN_USER', 'Ban User'), ('UNBAN_USER', 'Unban User'), ('MANUAL_SUBSCRIPTION', 'Manual Subscription Activation'), ('DEACTIVATE_CARD', 'Deactivate Card'), ('ACTIVATE_CARD', 'Activate Card'), ('TOGGLE_BIG_MATCH', 'Toggle Big Match'), ('BROADCAST_NOTIFICATION', 'Broadcast Notification'), ('CREATE_MATCH', 'Create Match'), ('UPDATE_MATCH', 'Update Match'), ('MAKE_ADMIN', 'Make Admin'), ('REVOKE_ADMIN', 'Revoke Admin'), ('CREATE_HERO_SLIDE', 'Create Hero Slide'), ('UPDATE_HERO_SLIDE', 'Update Hero Slide'), ('DELETE_HERO_SLIDE', 'Delete Hero Slide'), ('UPDATE_HERO_IMAGE', 'Update Hero Image')], max_length=30),
        ),
    ]
