# Generated by Django 5.0.6 on 2026-09-10 06:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(choices=[('WIN_3_TIPS', 'Win 3 Tips Today'), ('ACCURACY_70', 'Reach 70% Accuracy'), ('CREATE_5_TIPS', 'Create 5 Tips'), ('STREAK_3', 'Get 3 Correct Tips in a Row'), ('EARLY_BIRD', 'Be Among First 10 Users Today'), ('SOCIAL_SHARE', 'Share 3 Tips')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward_xp', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_value', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('challenge_date', models.DateField(db_index=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gamification_dailychallenge',
                'ordering': ['-challenge_date'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending - Not registered yet'), ('COMPLETED', 'Completed - Successfully registered'), ('EXPIRED', 'Expired - Code expired')], default='PENDING', max_length=20)),
                ('reward_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_referral',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('WHATSAPP', 'WhatsApp Share'), ('FACEBOOK', 'Facebook Share'), ('TWITTER', 'Twitter Share'), ('TELEGRAM', 'Telegram Share'), ('COPY_LINK', 'Copy Link')], max_length=20)),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.IntegerField()),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('reward_xp', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_socialshare',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('experience_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_level_xp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('next_level_xp', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_tips_created', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_tips_correct', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('longest_streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ai_agreement_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('social_shares_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('referral_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_userprogress',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('FIRST_WIN', 'First Winner - First correct tip'), ('STREAK_5', '5-Streak Master - 5 correct tips in a row'), ('STREAK_10', '10-Streak Legend - 10 correct tips in a row'), ('DERBY_SPECIALIST', 'Derby Specialist - Won a derby tip'), ('WEEKLY_CHAMPION', 'Weekly Champion - Top of weekly leaderboard'), ('MONTHLY_CHAMPION', 'Monthly Champion - Top of monthly leaderboard'), ('CENTURY_TIPSTER', 'Century Tipster - 100 tips total'), ('PERFECT_WEEK', 'Perfect Week - 100% accuracy in a week'), ('AI_MASTER', 'AI Master - High AI agreement score'), ('EARLY_BIRD', 'Early Bird - First 10 users daily'), ('SOCIAL_BUTTERFLY', 'Social Butterfly - 10 social shares'), ('REFERRAL_HERO', 'Referral Hero - 5 successful referrals')], max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_userachievement',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamification.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_userchallenge',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
