# Generated by Django 5.0.6 on 2026-09-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='current_streak',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='longest_streak',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='total_tips_correct',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='total_tips_created',
        ),
    ]
