# Generated by Django 5.0.6 on 2026-09-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_remove_userprogress_current_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='challenge_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailychallenge',
            unique_together={('challenge_date', 'challenge_type')},
        ),
    ]
