# Generated by Django 5.0.6 on 2026-09-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_alter_dailychallenge_challenge_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
