# Generated by Django 5.0.6 on 2026-09-08 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(default='/', max_length=500)),
                ('visit_date', models.DateField(db_index=True)),
                ('visited_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='visitorlog',
            constraint=models.UniqueConstraint(fields=('visitor_key', 'visit_date', 'path'), name='unique_visitor_path_per_day'),
        ),
    ]
